/** Persian labels + helper hints for the admin bot-settings editor. */

export const TEXT_LABELS: Record<string, string> = {
  welcome: "پیام خوش‌آمد (کاربر جدید)",
  welcomeBack: "پیام خوش‌آمد (بازگشت)",
  menuPrompt: "متن منوی اصلی",
  walletHeader: "سربرگ کیف پول",
  ordersHeader: "سربرگ سفارش‌ها",
  ordersEmpty: "سفارش‌ها خالی",
  flashHeader: "سربرگ فروشگاه",
  flashEmpty: "فروشگاه خالی",
  watchlistHeader: "سربرگ پیگیری‌ها",
  watchlistEmpty: "پیگیری‌ها خالی",
  depositPrompt: "راهنمای شارژ کیف پول",
  depositReceived: "تأیید ثبت واریز",
  withdrawPrompt: "راهنمای برداشت",
  withdrawReceived: "تأیید ثبت برداشت",
  linkSuccess: "اتصال موفق حساب",
  notifAuctionStarted: "اعلان: شروع مزایده",
  notifAuctionWon: "اعلان: برنده مزایده",
  notifOrderDelivered: "اعلان: تحویل سفارش",
  notifDepositApproved: "اعلان: تأیید واریز",
  notifWithdrawApproved: "اعلان: تأیید برداشت",
  purchaseSuccess: "خرید موفق",
  purchaseFailed: "خرید ناموفق",
  notRegistered: "کاربر ثبت‌نام‌نشده",
  help: "متن راهنما",
  chooseLanguage: "انتخاب زبان (منو)",
  chooseLanguageWelcome: "انتخاب زبان (شروع/خوش‌آمد)",
  languageSet: "تأیید تغییر زبان",
  joinRequired: "عضویت اجباری (شروع)",
  accessRevoked: "قطع دسترسی (خروج از کانال)",
  joinVerified: "تأیید عضویت موفق",
  joinNotYet: "هشدار: هنوز عضو نشده",
}

export const BUTTON_LABELS: Record<string, string> = {
  openApp: "باز کردن اپ",
  auctions: "مزایده‌ها",
  flash: "فروشگاه",
  wallet: "کیف پول",
  orders: "سفارش‌ها",
  watchlist: "پیگیری‌ها",
  deposit: "شارژ کیف پول",
  withdraw: "برداشت",
  help: "راهنما",
  back: "بازگشت",
  buy: "خرید فوری",
  refresh: "بروزرسانی",
  joinChannel: "عضویت در کانال",
  checkJoin: "بررسی عضویت",
}

export const FEATURE_LABELS: Record<string, { title: string; desc: string }> = {
  miniApp: { title: "مینی‌اپ", desc: "نمایش دکمه باز کردن وب‌اپ در ربات" },
  flashBrowse: { title: "مرور فروشگاه", desc: "نمایش و خرید محصولات در چت" },
  walletInChat: { title: "کیف پول در چت", desc: "مشاهده موجودی و سفارش‌ها در ربات" },
  deposits: { title: "شارژ کیف پول", desc: "ثبت درخواست واریز از داخل ربات" },
  withdrawals: { title: "برداشت", desc: "ثبت درخواست برداشت از داخل ربات" },
  notifications: { title: "اعلان‌ها", desc: "ارسال اعلان‌های زنده (مزایده، تحویل، مالی)" },
  forcedJoin: {
    title: "عضویت اجباری",
    desc: "کاربر باید قبل از استفاده در کانال‌های تعیین‌شده عضو باشد",
  },
}

export const EMOJI_LABELS: Record<string, string> = {
  wave: "دست تکان",
  fire: "آتش",
  gavel: "چکش مزایده",
  wallet: "کیف پول",
  money: "پول",
  party: "جشن",
  trophy: "جام",
  box: "جعبه",
  bell: "زنگ",
  eye: "چشم",
  rocket: "موشک",
  check: "تیک",
  cross: "ضربدر",
  clock: "ساعت",
  star: "ستاره",
  lightning: "صاعقه",
  gift: "هدیه",
  card: "کارت",
  sparkles: "درخشش",
  warning: "هشدار",
  lock: "قفل",
  chart: "نمودار",
  cart: "سبد خرید",
  globe: "کره زمین",
  megaphone: "بلندگو",
  link: "لینک",
  key: "کلید",
  point: "اشاره پایین",
  horizontal: "جابجایی افقی",
  alarm: "ساعت زنگ‌دار",
  bullet: "نشانگر کوچک",
  next: "صفحه بعد",
  previous: "صفحه قبل",
  forbidden: "ورود ممنوع",
  writing: "نوشتن",
  close: "بستن",
  question: "علامت سؤال",
  plus: "افزودن",
  minus: "کاستن",
  backArrow: "فلش بازگشت",
  sos: "پشتیبانی اضطراری",
  clover: "شبدر شانس",
  cinema: "ویدیو",
  target: "هدف",
  dice: "تاس",
  tag: "برچسب",
  user: "کاربر",
  users: "کاربران",
  chat: "گفتگو",
  cash: "اسکناس",
  note: "یادداشت",
  announce: "اعلان",
  refresh: "بروزرسانی",
  blue: "دایره آبی",
  emergency: "هشدار اضطراری",
  prohibited: "ممنوع",
  tools: "ابزار",
  shieldText: "سپر ساده",
  shield: "سپر",
  yellow: "دایره زرد",
  robot: "ربات",
  goldMedal: "مدال طلا",
  receipt: "رسید",
}
