import type { Locale } from "@/lib/i18n/locales"

const fa = {
  statuses: { AVAILABLE:"قابل ثبت",REGISTERED:"ثبت شده",UNSUPPORTED:"پشتیبانی نمی‌شود",UNKNOWN:"نامشخص",LOOKUP_ERROR:"بررسی ناموفق",ERROR:"بررسی ناموفق",PREMIUM:"ویژه و غیرقابل فروش",RESERVED:"رزرو شده",PENDING_PURCHASE:"در صف ثبت",PROCESSING:"در حال خرید",AWAITING_NAMESERVERS:"منتظر NS شما",AWAITING_NAMESERVER_SETUP:"در انتظار ثبت NS",COMPLETED:"تکمیل شده",FAILED:"ناموفق؛ بازپرداخت شد",EXPIRED:"منقضی؛ بازپرداخت شد" },
  nsRequired:"وارد کردن NS1 و NS2 الزامی است.",nsInvalid:"آدرس NS معتبر نیست؛ نمونه صحیح: ns1.example.com",nsUnique:"هر NS باید متفاوت باشد؛ NS1 و NS2 یکسان پذیرفته نمی‌شوند.",nsSaved:"NSها ثبت شد و درخواست برای ادمین ارسال گردید.",nsFailed:"ثبت NS انجام نشد.",amount:"مبلغ",purchased:"خرید",expires:"انقضا",nsAria:"ثبت نیم سرورها",nsTitle:"NSهای دامنه را ثبت کنید",nsDescription:"NS1 و NS2 الزامی هستند. می‌توانید این مرحله را اکنون یا هر زمان دیگری تکمیل کنید.",required:"الزامی",nsSubmit:"ثبت NS و ارسال برای ادمین",nsSent:"NSها برای ادمین ارسال شده‌اند",
} as const

type Copy = { [K in keyof typeof fa]: K extends "statuses" ? { [S in keyof typeof fa.statuses]: string } : string }

const en: Copy = { statuses:{AVAILABLE:"Available",REGISTERED:"Registered",UNSUPPORTED:"Unsupported",UNKNOWN:"Unknown",LOOKUP_ERROR:"Lookup failed",ERROR:"Lookup failed",PREMIUM:"Premium and unavailable",RESERVED:"Reserved",PENDING_PURCHASE:"Queued for registration",PROCESSING:"Purchasing",AWAITING_NAMESERVERS:"Waiting for your nameservers",AWAITING_NAMESERVER_SETUP:"Nameserver setup pending",COMPLETED:"Completed",FAILED:"Failed; refunded",EXPIRED:"Expired; refunded"},nsRequired:"NS1 and NS2 are required.",nsInvalid:"Enter a valid nameserver, such as ns1.example.com.",nsUnique:"Each nameserver must be unique.",nsSaved:"Nameservers submitted for setup.",nsFailed:"Nameservers could not be submitted.",amount:"Amount",purchased:"Purchased",expires:"Expires",nsAria:"Submit nameservers",nsTitle:"Add your domain nameservers",nsDescription:"NS1 and NS2 are required. You can complete this now or return later.",required:"Required",nsSubmit:"Submit nameservers",nsSent:"Nameservers were sent for setup" }
const ru: Copy = { statuses:{AVAILABLE:"Доступен",REGISTERED:"Зарегистрирован",UNSUPPORTED:"Не поддерживается",UNKNOWN:"Неизвестно",LOOKUP_ERROR:"Ошибка проверки",ERROR:"Ошибка проверки",PREMIUM:"Премиум, недоступен",RESERVED:"Зарезервирован",PENDING_PURCHASE:"В очереди на регистрацию",PROCESSING:"Покупка",AWAITING_NAMESERVERS:"Ожидаются ваши NS",AWAITING_NAMESERVER_SETUP:"Ожидается настройка NS",COMPLETED:"Завершено",FAILED:"Ошибка; возврат выполнен",EXPIRED:"Истёк; возврат выполнен"},nsRequired:"NS1 и NS2 обязательны.",nsInvalid:"Введите корректный NS, например ns1.example.com.",nsUnique:"Каждый NS должен быть уникальным.",nsSaved:"NS отправлены на настройку.",nsFailed:"Не удалось отправить NS.",amount:"Сумма",purchased:"Покупка",expires:"Истекает",nsAria:"Отправка NS",nsTitle:"Добавьте NS домена",nsDescription:"NS1 и NS2 обязательны. Это можно сделать сейчас или позже.",required:"Обязательно",nsSubmit:"Отправить NS",nsSent:"NS отправлены на настройку" }
const hi: Copy = { statuses:{AVAILABLE:"उपलब्ध",REGISTERED:"पंजीकृत",UNSUPPORTED:"समर्थित नहीं",UNKNOWN:"अज्ञात",LOOKUP_ERROR:"जाँच विफल",ERROR:"जाँच विफल",PREMIUM:"प्रीमियम, अनुपलब्ध",RESERVED:"आरक्षित",PENDING_PURCHASE:"पंजीकरण कतार में",PROCESSING:"खरीद जारी",AWAITING_NAMESERVERS:"आपके NS की प्रतीक्षा",AWAITING_NAMESERVER_SETUP:"NS सेटअप लंबित",COMPLETED:"पूरा हुआ",FAILED:"विफल; रिफंड किया गया",EXPIRED:"समाप्त; रिफंड किया गया"},nsRequired:"NS1 और NS2 आवश्यक हैं।",nsInvalid:"मान्य नेमसर्वर डालें, जैसे ns1.example.com।",nsUnique:"हर नेमसर्वर अलग होना चाहिए।",nsSaved:"नेमसर्वर सेटअप के लिए भेज दिए गए।",nsFailed:"नेमसर्वर भेजे नहीं जा सके।",amount:"राशि",purchased:"खरीदा",expires:"समाप्ति",nsAria:"नेमसर्वर भेजें",nsTitle:"डोमेन नेमसर्वर जोड़ें",nsDescription:"NS1 और NS2 आवश्यक हैं। इसे अभी या बाद में पूरा कर सकते हैं।",required:"आवश्यक",nsSubmit:"नेमसर्वर भेजें",nsSent:"नेमसर्वर सेटअप के लिए भेजे गए" }

export const DOMAIN_ORDER_COPY: Record<Locale, Copy> = { fa, en, hi, ru }
