import type { Locale } from "@/lib/i18n/locales"

const fa = {
  statuses: { AVAILABLE:"قابل ثبت",REGISTERED:"ثبت شده",UNSUPPORTED:"پشتیبانی نمی‌شود",UNKNOWN:"نامشخص",LOOKUP_ERROR:"بررسی ناموفق",ERROR:"بررسی ناموفق",PREMIUM:"ویژه و غیرقابل فروش",RESERVED:"رزرو شده",PENDING_PURCHASE:"در صف ثبت",PROCESSING:"در حال خرید",AWAITING_NAMESERVERS:"منتظر NS شما",AWAITING_NAMESERVER_SETUP:"در انتظار ثبت NS",COMPLETED:"تکمیل شده",FAILED:"ناموفق؛ بازپرداخت شد",EXPIRED:"منقضی؛ بازپرداخت شد" },
  nsRequired:"وارد کردن NS1 و NS2 الزامی است.",nsInvalid:"آدرس NS معتبر نیست؛ نمونه صحیح: ns1.example.com",nsUnique:"هر NS باید متفاوت باشد؛ NS1 و NS2 یکسان پذیرفته نمی‌شوند.",nsSaved:"NSها ثبت شد و درخواست برای ادمین ارسال گردید.",nsFailed:"ثبت NS انجام نشد.",amount:"مبلغ",purchased:"خرید",expires:"انقضا",nsAria:"مدیریت نیم‌سرورها",nsTitle:"نیم‌سرورهای دامنه (NS)",nsDescription:"NS1 و NS2 الزامی هستند. هر بار که ثبت یا تغییر دهید، یک درخواست برای تایید مدیر ساخته می‌شود.",required:"الزامی",nsSubmit:"ارسال درخواست ثبت/تغییر NS",nsSent:"NSهای فعال روی دامنه",
  // Timer + waiting states (product-parity)
  timerTitle:"مهلت خرید توسط مدیر",timeLeft:"زمان باقی‌مانده",overdue:"مهلت به پایان رسید",waitTitle:"در انتظار خرید دامنه",waitBody:"مبلغ در کیف پول شما مسدود شده است. الان باید منتظر خرید دامنه توسط مدیر باشید؛ نتیجه به‌زودی همین‌جا نمایش داده می‌شود.",
  // NS manager
  liveNsTitle:"نیم‌سرورهای فعال",noLiveNs:"هنوز نیم‌سروری روی این دامنه ثبت نشده است.",nsLockedTitle:"مدیریت نیم‌سرور پس از ثبت دامنه فعال می‌شود",nsLockedBody:"به‌محض تکمیل خرید، می‌توانید نیم‌سرورهای دامنه را از همین‌جا ثبت و تغییر دهید.",nsUpdatedAt:"آخرین به‌روزرسانی NS",
  // NS request history + statuses
  nsHistoryTitle:"درخواست‌های تغییر NS",nsReqPending:"در انتظار تایید مدیر",nsReqCompleted:"ثبت شد",nsReqRejected:"رد شد",nsReqCancelled:"جایگزین شد",nsReqRejectReason:"دلیل رد",
} as const

type Copy = { [K in keyof typeof fa]: K extends "statuses" ? { [S in keyof typeof fa.statuses]: string } : string }

const en: Copy = { statuses:{AVAILABLE:"Available",REGISTERED:"Registered",UNSUPPORTED:"Unsupported",UNKNOWN:"Unknown",LOOKUP_ERROR:"Lookup failed",ERROR:"Lookup failed",PREMIUM:"Premium and unavailable",RESERVED:"Reserved",PENDING_PURCHASE:"Queued for registration",PROCESSING:"Purchasing",AWAITING_NAMESERVERS:"Waiting for your nameservers",AWAITING_NAMESERVER_SETUP:"Nameserver setup pending",COMPLETED:"Completed",FAILED:"Failed; refunded",EXPIRED:"Expired; refunded"},nsRequired:"NS1 and NS2 are required.",nsInvalid:"Enter a valid nameserver, such as ns1.example.com.",nsUnique:"Each nameserver must be unique.",nsSaved:"Nameservers submitted for setup.",nsFailed:"Nameservers could not be submitted.",amount:"Amount",purchased:"Purchased",expires:"Expires",nsAria:"Manage nameservers",nsTitle:"Domain nameservers (NS)",nsDescription:"NS1 and NS2 are required. Each time you submit or change them, a request is created for the admin to approve.",required:"Required",nsSubmit:"Submit NS change request",nsSent:"Live nameservers on the domain",timerTitle:"Time left for admin to register",timeLeft:"Time remaining",overdue:"Time is up",waitTitle:"Waiting for domain registration",waitBody:"Funds are held in your wallet. Now please wait for the admin to register the domain — the result will appear here shortly.",liveNsTitle:"Active nameservers",noLiveNs:"No nameservers have been set on this domain yet.",nsLockedTitle:"Nameserver management unlocks after registration",nsLockedBody:"Once the purchase completes, you can submit and change the domain nameservers right here.",nsUpdatedAt:"NS last updated",nsHistoryTitle:"Nameserver change requests",nsReqPending:"Awaiting admin approval",nsReqCompleted:"Applied",nsReqRejected:"Rejected",nsReqCancelled:"Superseded",nsReqRejectReason:"Rejection reason" }
const ru: Copy = { statuses:{AVAILABLE:"Доступен",REGISTERED:"Зарегистрирован",UNSUPPORTED:"Не поддерживается",UNKNOWN:"Неизвестно",LOOKUP_ERROR:"Ошибка проверки",ERROR:"Ошибка проверки",PREMIUM:"Премиум, недоступен",RESERVED:"Зарезервирован",PENDING_PURCHASE:"В очереди на регистрацию",PROCESSING:"Покупка",AWAITING_NAMESERVERS:"Ожидаются ваши NS",AWAITING_NAMESERVER_SETUP:"Ожидается настройка NS",COMPLETED:"Завершено",FAILED:"Ошибка; возврат выполнен",EXPIRED:"Истёк; возврат выполнен"},nsRequired:"NS1 и NS2 обязательны.",nsInvalid:"Введите корректный NS, например ns1.example.com.",nsUnique:"Каждый NS должен быть уникальным.",nsSaved:"NS отправлены на настройку.",nsFailed:"Не удалось отправить NS.",amount:"Сумма",purchased:"Покупка",expires:"Истекает",nsAria:"Управление NS",nsTitle:"Nameservers домена (NS)",nsDescription:"NS1 и NS2 обязательны. При каждой отправке или изменении создаётся заявка на подтверждение админом.",required:"Обязательно",nsSubmit:"Отправить заявку на изменение NS",nsSent:"Активные NS домена",timerTitle:"Время на регистрацию админом",timeLeft:"Осталось времени",overdue:"Время истекло",waitTitle:"Ожидание регистрации домена",waitBody:"Средства заморожены в кошельке. Теперь дождитесь регистрации домена админом — результат скоро появится здесь.",liveNsTitle:"Активные nameservers",noLiveNs:"Для этого домена ещё не заданы nameservers.",nsLockedTitle:"Управление NS откроется после регистрации",nsLockedBody:"После завершения покупки вы сможете задавать и менять nameservers прямо здесь.",nsUpdatedAt:"NS обновлены",nsHistoryTitle:"Заявки на изменение NS",nsReqPending:"Ожидает подтверждения админом",nsReqCompleted:"Применено",nsReqRejected:"Отклонено",nsReqCancelled:"Заменено",nsReqRejectReason:"Причина отклонения" }
const hi: Copy = { statuses:{AVAILABLE:"उपलब्ध",REGISTERED:"पंजीकृत",UNSUPPORTED:"समर्थित नहीं",UNKNOWN:"अज्ञात",LOOKUP_ERROR:"जाँच विफल",ERROR:"जाँच विफल",PREMIUM:"प्रीमियम, अनुपलब्ध",RESERVED:"आरक्षित",PENDING_PURCHASE:"पंजीकरण कतार में",PROCESSING:"खरीद जारी",AWAITING_NAMESERVERS:"आपके NS की प्रतीक्षा",AWAITING_NAMESERVER_SETUP:"NS सेटअप लंबित",COMPLETED:"पूरा हुआ",FAILED:"विफल; रिफंड किया गया",EXPIRED:"समाप्त; रिफंड किया गया"},nsRequired:"NS1 और NS2 आवश्यक हैं।",nsInvalid:"मान्य नेमसर्वर डालें, जैसे ns1.example.com।",nsUnique:"हर नेमसर्वर अलग होना चाहिए।",nsSaved:"नेमसर्वर सेटअप के लिए भेज दिए गए।",nsFailed:"नेमसर्वर भेजे नहीं जा सके।",amount:"राशि",purchased:"खरीदा",expires:"समाप्ति",nsAria:"नेमसर्वर प्रबंधन",nsTitle:"डोमेन नेमसर्वर (NS)",nsDescription:"NS1 और NS2 आवश्यक हैं। हर बार जमा या बदलने पर एडमिन की स्वीकृति हेतु अनुरोध बनता है।",required:"आवश्यक",nsSubmit:"NS बदलाव अनुरोध भेजें",nsSent:"डोमेन पर सक्रिय नेमसर्वर",timerTitle:"एडमिन द्वारा पंजीकरण का समय",timeLeft:"शेष समय",overdue:"समय समाप्त",waitTitle:"डोमेन पंजीकरण की प्रतीक्षा",waitBody:"राशि आपके वॉलेट में रोकी गई है। अब कृपया एडमिन द्वारा डोमेन पंजीकरण की प्रतीक्षा करें — परिणाम यहीं दिखेगा।",liveNsTitle:"सक्रिय नेमसर्वर",noLiveNs:"इस डोमेन पर अभी कोई नेमसर्वर सेट नहीं है।",nsLockedTitle:"पंजीकरण के बाद नेमसर्वर प्रबंधन सक्रिय होगा",nsLockedBody:"खरीद पूरी होते ही आप यहीं से डोमेन नेमसर्वर जमा और बदल सकेंगे।",nsUpdatedAt:"NS अंतिम अपडेट",nsHistoryTitle:"नेमसर्वर बदलाव अनुरोध",nsReqPending:"एडमिन स्वीकृति प्रतीक्षित",nsReqCompleted:"लागू किया गया",nsReqRejected:"अस्वीकृत",nsReqCancelled:"प्रतिस्थापित",nsReqRejectReason:"अस्वीकृति कारण" }

export const DOMAIN_ORDER_COPY: Record<Locale, Copy> = { fa, en, hi, ru }
