import { Prisma } from "@prisma/client"
import { prisma } from "@/lib/db"
import { secureSlug } from "@/lib/id"
import { NotFoundError, ValidationError } from "./errors"
import { audit } from "./audit"
import { cancelAuctionAndRelease } from "./auction"
import { enqueueTranslations } from "@/lib/i18n/content-translation"

// --- Listing -----------------------------------------------------------------

export async function listProductsAdmin() {
  return prisma.product.findMany({
    orderBy: { createdAt: "desc" },
    take: 200,
    include: {
      fixedSale: true,
      auction: { include: { _count: { select: { bids: true } } } },
      _count: { select: { inventoryItems: true, orders: true } },
    },
  })
}

export async function getProductAdmin(id: string) {
  const product = await prisma.product.findUnique({
    where: { id },
    include: {
      fixedSale: true,
      auction: true,
      defaultTutorial: { select: { id: true, title: true, slug: true } },
      variants: { orderBy: [{ displayOrder: "asc" }, { createdAt: "asc" }] },
    },
  })
  if (!product) throw new NotFoundError("محصول یافت نشد")
  return product
}

/**
 * Update only the media of any product (works for both fixed-price and auction
 * products, unlike updateFlashProduct which requires a FixedSale). Pass a field
 * to change it; omit to leave it untouched.
 */
export async function updateProductMedia(
  productId: string,
  input: { coverImage?: string | null; gallery?: string[] },
  adminId: string,
) {
  const product = await prisma.product.findUnique({ where: { id: productId } })
  if (!product) throw new NotFoundError("محصول یافت نشد")
  const updated = await prisma.product.update({
    where: { id: productId },
    data: {
      coverImage: input.coverImage !== undefined ? input.coverImage || null : undefined,
      gallery: input.gallery !== undefined ? input.gallery.filter(Boolean).slice(0, 12) : undefined,
    },
    include: { fixedSale: true, auction: true },
  })
  await audit({ actorId: adminId, action: "product.media.update", entity: "product", entityId: productId })
  return updated
}

// --- Flash-sale (fixed price) product ---------------------------------------

export interface ProductLinkInput {
  label: string
  url: string
}

export interface FlashProductInput {
  title: string
  description?: string
  category?: string
  tags?: string[]
  gallery?: string[]
  // Native multilingual copy generated by the AI Copilot (fa/en/ru/hi).
  i18n?: Prisma.InputJsonValue | null
  coverImage?: string
  deliveryType: "MANUAL" | "AUTOMATIC"
  price: bigint
  stock: number
  purchaseLimit?: number | null
  links?: ProductLinkInput[]
  soldBaseline?: number
  bulkMinQty?: number | null
  bulkDiscountPercent?: number | null
  hidden?: boolean
}

/** Clean a tag list: trim, drop empties, cap at 12. */
function cleanTags(tags?: string[]): string[] {
  if (!Array.isArray(tags)) return []
  return Array.from(new Set(tags.map((t) => (t ?? "").trim()).filter(Boolean))).slice(0, 12)
}

/** Clean a gallery URL list: drop empties, cap at 12. */
function cleanGallery(gallery?: string[]): string[] {
  if (!Array.isArray(gallery)) return []
  return gallery.map((g) => (g ?? "").trim()).filter(Boolean).slice(0, 12)
}

/** Sanitize labeled links: keep only entries with both a label and a URL. */
function cleanLinks(links?: ProductLinkInput[]): Prisma.InputJsonValue {
  if (!Array.isArray(links)) return []
  return links
    .map((l) => ({ label: (l.label ?? "").trim(), url: (l.url ?? "").trim() }))
    .filter((l) => l.label && l.url)
    .slice(0, 8)
}

function queueProductTranslation(product: {
  id: string
  title: string
  description: string | null
  category: string | null
  tags: string[]
  links: Prisma.JsonValue | null
}) {
  return enqueueTranslations({
    entityType: "product",
    entityId: product.id,
    sourceData: {
      title: product.title,
      description: product.description,
      category: product.category,
      tags: product.tags,
      links: product.links,
    },
  })
}

export async function createFlashProduct(input: FlashProductInput, adminId: string) {
  if (!input.title.trim()) throw new ValidationError("عنوان الزامی است")
  if (input.price <= 0n) throw new ValidationError("قیمت باید بزرگ‌تر از صفر باشد")
  const product = await prisma.product.create({
    data: {
      slug: secureSlug("p"),
      title: input.title.trim(),
      description: input.description,
      category: input.category,
      tags: cleanTags(input.tags),
      gallery: cleanGallery(input.gallery),
      i18n: input.i18n ?? Prisma.DbNull,
      coverImage: input.coverImage,
      links: cleanLinks(input.links),
      saleMode: "FIXED_PRICE",
      deliveryType: input.deliveryType,
      hidden: input.hidden ?? false,
      fixedSale: {
        create: {
          price: input.price,
          stock: input.stock,
          purchaseLimit: input.purchaseLimit ?? null,
          soldBaseline: Math.max(0, input.soldBaseline ?? 0),
          bulkMinQty: input.bulkMinQty ?? null,
          bulkDiscountPercent: input.bulkDiscountPercent ?? null,
        },
      },
    },
    include: { fixedSale: true },
  })
  await audit({ actorId: adminId, action: "product.create", entity: "product", entityId: product.id, meta: { mode: "FIXED_PRICE" } })
  await queueProductTranslation(product)
  // Notify followers of this category about the new product (visible only).
  if (!product.hidden && product.category) {
    try {
      const { notifyNewProduct } = await import("./category-follows")
      await notifyNewProduct({
        productId: product.id,
        title: product.title,
        category: product.category,
        coverImage: product.coverImage,
      })
    } catch (e) {
      console.log("[v0] notifyNewProduct (flash) error:", (e as Error).message)
    }
  }
  return product
}

export interface FlashUpdateInput {
  title?: string
  description?: string
  category?: string
  tags?: string[]
  gallery?: string[]
  i18n?: Prisma.InputJsonValue | null
  coverImage?: string
  price?: bigint
  stock?: number
  purchaseLimit?: number | null
  links?: ProductLinkInput[]
  soldBaseline?: number
  bulkMinQty?: number | null
  bulkDiscountPercent?: number | null
  hidden?: boolean
  active?: boolean
}

export async function updateFlashProduct(productId: string, input: FlashUpdateInput, adminId: string) {
  const product = await prisma.product.findUnique({ where: { id: productId }, include: { fixedSale: true } })
  if (!product || !product.fixedSale) throw new NotFoundError("محصول فروشگاه یافت نشد")
  const updated = await prisma.product.update({
    where: { id: productId },
    data: {
      title: input.title?.trim() ?? undefined,
      description: input.description,
      category: input.category,
      tags: input.tags !== undefined ? cleanTags(input.tags) : undefined,
      gallery: input.gallery !== undefined ? cleanGallery(input.gallery) : undefined,
      i18n: input.i18n === undefined ? undefined : (input.i18n ?? Prisma.DbNull),
      coverImage: input.coverImage,
      links: input.links !== undefined ? cleanLinks(input.links) : undefined,
      hidden: input.hidden,
      active: input.active,
      fixedSale: {
        update: {
          price: input.price,
          stock: input.stock,
          purchaseLimit: input.purchaseLimit,
          soldBaseline: input.soldBaseline !== undefined ? Math.max(0, input.soldBaseline) : undefined,
          bulkMinQty: input.bulkMinQty,
          bulkDiscountPercent: input.bulkDiscountPercent,
        },
      },
    },
    include: { fixedSale: true },
  })
  await audit({ actorId: adminId, action: "product.update", entity: "product", entityId: productId })
  await queueProductTranslation(updated)
  // Fire back-in-stock alerts if this update made the product available again.
  try {
    const { reconcileStockAlerts } = await import("./stock-alerts")
    await reconcileStockAlerts(productId)
  } catch (e) {
    console.log("[v0] reconcileStockAlerts (update) error:", (e as Error).message)
  }
  return updated
}

// --- Auction product ---------------------------------------------------------

export interface AuctionProductInput {
  title: string
  description?: string
  category?: string
  tags?: string[]
  gallery?: string[]
  i18n?: Prisma.InputJsonValue | null
  coverImage?: string
  deliveryType: "MANUAL" | "AUTOMATIC"
  startPrice: bigint
  minimumIncrement: bigint
  reservePrice?: bigint | null
  buyNowPrice?: bigint | null
  quantity: number
  startTime: Date
  endTime: Date
  antiSnipingEnabled?: boolean
  hidden?: boolean
}

export async function createAuctionProduct(input: AuctionProductInput, adminId: string) {
  if (!input.title.trim()) throw new ValidationError("عنوان الزامی است")
  if (input.startPrice <= 0n) throw new ValidationError("قیمت پایه باید بزرگ‌تر از صفر باشد")
  if (input.endTime <= input.startTime) throw new ValidationError("زمان پایان باید بعد از شروع باشد")
  if (input.quantity < 1) throw new ValidationError("تعداد برنده باید حداقل ۱ باشد")

  const now = new Date()
  const status = input.startTime <= now ? "ACTIVE" : "SCHEDULED"

  const product = await prisma.product.create({
    data: {
      slug: secureSlug("p"),
      title: input.title.trim(),
      description: input.description,
      category: input.category,
      tags: cleanTags(input.tags),
      gallery: cleanGallery(input.gallery),
      i18n: input.i18n ?? Prisma.DbNull,
      coverImage: input.coverImage,
      saleMode: "AUCTION",
      deliveryType: input.deliveryType,
      hidden: input.hidden ?? false,
      auction: {
        create: {
          startPrice: input.startPrice,
          minimumIncrement: input.minimumIncrement,
          reservePrice: input.reservePrice ?? null,
          buyNowPrice: input.buyNowPrice ?? null,
          quantity: input.quantity,
          startTime: input.startTime,
          endTime: input.endTime,
          antiSnipingEnabled: input.antiSnipingEnabled ?? true,
          status,
        },
      },
    },
    include: { auction: true },
  })
  await audit({ actorId: adminId, action: "product.create", entity: "product", entityId: product.id, meta: { mode: "AUCTION" } })
  await queueProductTranslation(product)
  // Notify category followers about the new auction (visible only).
  if (!product.hidden && product.category) {
    try {
      const { notifyNewProduct } = await import("./category-follows")
      await notifyNewProduct({
        productId: product.id,
        title: product.title,
        category: product.category,
        coverImage: product.coverImage,
        href: `/auctions/${product.auction!.id}`,
      })
    } catch (e) {
      console.log("[v0] notifyNewProduct (auction) error:", (e as Error).message)
    }
  }
  return product
}

/** Cancel an auction that has not been finalized, releasing all frozen holds. */
export async function cancelAuction(auctionId: string, adminId: string) {
  const res = await cancelAuctionAndRelease(auctionId)
  await audit({
    actorId: adminId,
    action: "auction.cancel",
    entity: "auction",
    entityId: auctionId,
    meta: { released: res.released },
  })
  return res
}

export async function setProductDefaultTutorial(
  productId: string,
  tutorialId: string | null,
  adminId: string,
) {
  const product = await prisma.product.findUnique({ where: { id: productId }, select: { id: true } })
  if (!product) throw new NotFoundError("محصول یافت نشد")
  if (tutorialId) {
    const tutorial = await prisma.content.findFirst({
      where: { id: tutorialId, type: "tutorial", status: "PUBLISHED" },
      select: { id: true },
    })
    if (!tutorial) throw new ValidationError("آموزش منتشرشده معتبر نیست")
  }
  const updated = await prisma.product.update({
    where: { id: productId },
    data: { defaultTutorialId: tutorialId },
    include: { defaultTutorial: { select: { id: true, title: true, slug: true } } },
  })
  await audit({
    actorId: adminId,
    action: "product.tutorial.update",
    entity: "product",
    entityId: productId,
    meta: { tutorialId },
  })
  return updated
}

export async function setProductVisibility(productId: string, hidden: boolean, adminId: string) {
  const product = await prisma.product.findUnique({ where: { id: productId } })
  if (!product) throw new NotFoundError("محصول یافت نشد")
  await prisma.product.update({ where: { id: productId }, data: { hidden } })
  await audit({ actorId: adminId, action: "product.visibility", entity: "product", entityId: productId, meta: { hidden } })
}

// --- Deletion (single + bulk) ------------------------------------------------

export interface DeleteResult {
  deleted: string[]
  /** Items that could not be deleted, with a human-readable Persian reason. */
  skipped: { id: string; title: string; reason: string }[]
}

/**
 * Delete one or more products (fixed-price or auction) by id.
 *
 * Financial-safety guard: a product that has any associated orders is NEVER
 * hard-deleted (that would destroy purchase/settlement history). Such items are
 * returned in `skipped` with a clear reason so the admin can hide them instead.
 * All other relations (fixedSale, auction, bids, inventory, reviews, ...)
 * cascade automatically via the schema. Deletion of each product is atomic; the
 * loop is best-effort so one failure does not abort the rest of the batch.
 */
export async function deleteProducts(
  ids: string[],
  adminId: string,
  options: { reversePurchases?: boolean } = {},
): Promise<DeleteResult> {
  const unique = Array.from(new Set(ids.filter(Boolean)))
  const result: DeleteResult = { deleted: [], skipped: [] }
  if (unique.length === 0) return result

  const products = await prisma.product.findMany({
    where: { id: { in: unique } },
    select: {
      id: true,
      title: true,
      saleMode: true,
      _count: { select: { orders: true } },
    },
  })
  const byId = new Map(products.map((p) => [p.id, p]))

  for (const id of unique) {
    const product = byId.get(id)
    if (!product) {
      result.skipped.push({ id, title: id, reason: "یافت نشد" })
      continue
    }
    if (product._count.orders > 0 && !options.reversePurchases) {
      result.skipped.push({
        id,
        title: product.title,
        reason: `دارای ${product._count.orders} سفارش ثبت‌شده است؛ برای حفظ سوابق مالی حذف نشد. آن را مخفی کنید.`,
      })
      continue
    }
    if (product._count.orders > 0) {
      const { cleanupProductOrders } = await import("./admin/test-cleanup")
      const cleanup = await cleanupProductOrders(id, adminId)
      if (cleanup.skipped.length > 0) {
        result.skipped.push({ id, title: product.title, reason: cleanup.skipped[0].reason })
        continue
      }
    }
    try {
      await prisma.product.delete({ where: { id } })
      result.deleted.push(id)
      await audit({
        actorId: adminId,
        action: "product.delete",
        entity: "product",
        entityId: id,
        meta: { mode: product.saleMode, title: product.title },
      })
    } catch (e) {
      console.log("[v0] deleteProducts error for", id, (e as Error).message)
      result.skipped.push({ id, title: product.title, reason: "حذف به دلیل وابستگی داده‌ها ممکن نشد" })
    }
  }

  return result
}
